name: "Build and Test"

on:
  pull_request:
    branches: ['master']

permissions:
  contents: read

jobs:
  build-java-8:
    runs-on: ubuntu-latest
    permissions:
      contents: read  
      pull-requests: read
    timeout-minutes: 130
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up JDK 8
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Setup Develocity
        uses: gradle/develocity-actions/setup-maven@974e8dbcbda40db6828fc35f349c80a7c0e71529 # v2.1
      - name: Build with Apache Maven
        run: mvn -U clean install -Djava.awt.headless=true -fae -B --no-transfer-progress
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DIRECTORY_DEVELOCITY_ACCESS_KEY }}
    env: 
       MAVEN_OPTS: "-Xmx1024M"
  build-java-17:
    runs-on: ubuntu-latest
    permissions:
      contents: read  
      pull-requests: read
    timeout-minutes: 130
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up JDK 17
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Setup Develocity
        uses: gradle/develocity-actions/setup-maven@974e8dbcbda40db6828fc35f349c80a7c0e71529 # v2.1
      - name: Build with Apache Maven
        run: mvn -U clean install -Djava.awt.headless=true -fae -B --no-transfer-progress
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DIRECTORY_DEVELOCITY_ACCESS_KEY }}
